"""
Contains all the answers for the question in the help menu which is imported in the main file.
"""

view = "Click View. You will see the top 3 rankings in the table and"
view2 = "you can search a specific student\'s details in the search bar"
edit = "Click update. You can select the name for which you want"
edit2 = "to update points and select the events attended and the date of attendance."
home = "Click the Student Genius logo on the top left corner to go"
home2 = "back to the home screen."
wins = "Click View -> \'Show Winners\'. You will see the student with"
wins2 = "top point accumulation and a random winner from each grade for that quarter."
report = "Click View -> \'Generate Report\'. You will access the report"
report2 = "for that quarter."
Qview = "How to see the details of a student?"
Qedit = "How to add points to a student."
Qhome = "How to navigate back to home screen?"
Qwins = "How to view the winners for that quarter?"
Qreport = "How to generate a report for that quarter?"